### ISSUE TITLE
语法设计建议

### ISSUE THREAD

**Issue by Seng-Jik** [qwas982/Design-Brand-new-Chinese-characters-programme-Language#4]
令 全体斐波纳数 为 递推展开 (函 (a,b) -> 存在(a,(a+b,a))) (1,0)

// 其中：
// 递推展开 : ('状态 -> ('值,'状态) 可能) -> '状态 -> '值 数组
// 存在 : '值 -> '值 可能

全体斐波纳数
|> 切片 0 10
|> 遍历 (打印 "%d ")

// 其中
// 切片 : 起始下标:整数 -> 终结下标:整数 -> '值 数组 -> '值 数组
// 遍历 : ('值 -> 空) -> '值 数组
// 打印 : 'T 格式串 -> 'T -> 空

类似以上这种写法，参考语言：FSharp

**Comment by qwas982** [comment]
经过对基础情况的长足了解,我发现要建立中文汉字汉语编程远远没有想的那么简单,不仅仅是语法这一方面那么简单,别说中文汉字汉语,即便是用英文或西文字母创造的编程语言,我国也是几乎处于一片空白的状态.我找不到相关文档和具体实例,我不知道为啥我国对软件对编程设计这方面如此空洞苍白无力,几乎等于零,完全就是零.就这样还在整天嚷嚷要和美国人斗.
以程序设计程序开发的角度来解析计算机的计算过程计算技术这样的中文汉字汉语文章或书籍我没找到,也就是零.在这样的一穷二白的情况下就空谈高级语言语法无异于空中楼阁.
我换了系统(win10 Linux)才知道,对于大多数人,包括部分码农们,TA们连一个基本的中文汉字汉语输入的问题都没找到起码的解决方案.TA们连输入法都了解不详,我就奇怪为啥与这类反对中文汉字汉语编程的人争论时,TA们总是抛出字符输入时中文汉字汉语是劣势,中文汉字汉语的存储相对于英文西文来说也是劣势等言论.
这些人其实连一个基本的稳定的基于中文汉字汉语的作业环境都没有.
为此,我认为当前考虑的重点应该是回到二进制数字与中文汉字汉语的一一对应,也就是基本输入输出的解决上才是,
利用已有工具建立这么一个基础范畴.

**Comment by SmallLuma** [comment]
> 
> 
> 经过对基础情况的长足了解,我发现要建立中文汉字汉语编程远远没有想的那么简单,不仅仅是语法这一方面那么简单,别说中文汉字汉语,即便是用英文或西文字母创造的编程语言,我国也是几乎处于一片空白的状态.我找不到相关文档和具体实例,我不知道为啥我国对软件对编程设计这方面如此空洞苍白无力,几乎等于零,完全就是零.就这样还在整天嚷嚷要和美国人斗.
> 以程序设计程序开发的角度来解析计算机的计算过程计算技术这样的中文汉字汉语文章或书籍我没找到,也就是零.在这样的一穷二白的情况下就空谈高级语言语法无异于空中楼阁.
> 我换了系统(win10 Linux)才知道,对于大多数人,包括部分码农们,TA们连一个基本的中文汉字汉语输入的问题都没找到起码的解决方案.TA们连输入法都了解不详,我就奇怪为啥与这类反对中文汉字汉语编程的人争论时,TA们总是抛出字符输入时中文汉字汉语是劣势,中文汉字汉语的存储相对于英文西文来说也是劣势等言论.
> 这些人其实连一个基本的稳定的基于中文汉字汉语的作业环境都没有.
> 为此,我认为当前考虑的重点应该是回到二进制数字与中文汉字汉语的一一对应,也就是基本输入输出的解决上才是,
> 利用已有工具建立这么一个基础范畴.

那么你什么时候开始做呢
